packages:
  - "apps/*"
  - "packages/*"

autoInstallPeers: false

allowBuilds:
  "@prisma/client": false
  better-sqlite3: false
  esbuild: true
  lightningcss: true
  msw: false
  unrs-resolver: true

patchedDependencies:
  "@codemirror/merge@6.12.2": patches/@codemirror__merge@6.12.2.patch
