packages:
  - "apps/*"
  - "packages/*"

autoInstallPeers: false

allowBuilds:
  "@prisma/client": false
  better-sqlite3: false
  esbuild: true
  lightningcss: true
  msw: false
  unrs-resolver: true

patchedDependencies:
  "@codemirror/merge@6.12.2": patches/@codemirror__merge@6.12.2.patch
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vitest: 4.1.10
  vite-plus: 0.2.5
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
