/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as FilesRouteImport } from './routes/files'
import { Route as GithubRouteImport } from './routes/github'
import { Route as InfoRouteImport } from './routes/info'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TwitterRouteImport } from './routes/twitter'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as XRouteImport } from './routes/x'
import { Route as AppSplatRouteImport } from './routes/_app.$'
import { Route as AppAccessRouteImport } from './routes/_app.access'
import { Route as AppBricksRouteImport } from './routes/_app.bricks'
import { Route as AppSecurityRouteImport } from './routes/_app.security'
import { Route as AppServersRouteImport } from './routes/_app.servers'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiSentryCheckRouteImport } from './routes/api.sentry-check'
import { Route as AppServerServerIdRouteImport } from './routes/_app/server/$serverId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app.settings.account'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app.settings.appearance'
import { Route as AppSettingsBillingRouteImport } from './routes/_app.settings.billing'
import { Route as AppSettingsRelaysRouteImport } from './routes/_app.settings.relays'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiConsoleInstanceIdRouteImport } from './routes/api.console.$instanceId'
import { Route as AppServerServerIdIndexRouteImport } from './routes/_app/server/$serverId.index'
import { Route as AppServerServerIdSplatRouteImport } from './routes/_app/server/$serverId.$'
import { Route as AppServerServerIdConsoleRouteImport } from './routes/_app/server/$serverId.console'
import { Route as AppServerServerIdFilesRouteImport } from './routes/_app/server/$serverId.files'
import { Route as AppServerServerIdInfoRouteImport } from './routes/_app/server/$serverId.info'
import { Route as AppServerServerIdNetworkRouteImport } from './routes/_app/server/$serverId.network'
import { Route as AppServerServerIdFilesSplatRouteImport } from './routes/_app/server/$serverId.files.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TwitterRoute = TwitterRouteImport.update({
  id: '/twitter',
  path: '/twitter',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const XRoute = XRouteImport.update({
  id: '/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AppBricksRoute = AppBricksRouteImport.update({
  id: '/bricks',
  path: '/bricks',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppServersRoute = AppServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentryCheckRoute = ApiSentryCheckRouteImport.update({
  id: '/api/sentry-check',
  path: '/api/sentry-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServerServerIdRoute = AppServerServerIdRouteImport.update({
  id: '/server/$serverId',
  path: '/server/$serverId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsRelaysRoute = AppSettingsRelaysRouteImport.update({
  id: '/relays',
  path: '/relays',
  getParentRoute: () => AppSettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsoleInstanceIdRoute = ApiConsoleInstanceIdRouteImport.update({
  id: '/api/console/$instanceId',
  path: '/api/console/$instanceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServerServerIdIndexRoute = AppServerServerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppServerServerIdRoute,
} as any)
const AppServerServerIdSplatRoute = AppServerServerIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppServerServerIdRoute,
} as any)
const AppServerServerIdConsoleRoute =
  AppServerServerIdConsoleRouteImport.update({
    id: '/console',
    path: '/console',
    getParentRoute: () => AppServerServerIdRoute,
  } as any)
const AppServerServerIdFilesRoute = AppServerServerIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppServerServerIdRoute,
} as any)
const AppServerServerIdInfoRoute = AppServerServerIdInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AppServerServerIdRoute,
} as any)
const AppServerServerIdNetworkRoute =
  AppServerServerIdNetworkRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => AppServerServerIdRoute,
  } as any)
const AppServerServerIdFilesSplatRoute =
  AppServerServerIdFilesSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AppServerServerIdFilesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/discord': typeof DiscordRoute
  '/files': typeof FilesRoute
  '/github': typeof GithubRoute
  '/info': typeof InfoRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/twitter': typeof TwitterRoute
  '/two-factor': typeof TwoFactorRoute
  '/x': typeof XRoute
  '/$': typeof AppSplatRoute
  '/access': typeof AppAccessRoute
  '/bricks': typeof AppBricksRoute
  '/security': typeof AppSecurityRoute
  '/servers': typeof AppServersRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/sentry-check': typeof ApiSentryCheckRoute
  '/server/$serverId': typeof AppServerServerIdRouteWithChildren
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/relays': typeof AppSettingsRelaysRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/console/$instanceId': typeof ApiConsoleInstanceIdRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/server/$serverId/$': typeof AppServerServerIdSplatRoute
  '/server/$serverId/console': typeof AppServerServerIdConsoleRoute
  '/server/$serverId/files': typeof AppServerServerIdFilesRouteWithChildren
  '/server/$serverId/info': typeof AppServerServerIdInfoRoute
  '/server/$serverId/network': typeof AppServerServerIdNetworkRoute
  '/server/$serverId/': typeof AppServerServerIdIndexRoute
  '/server/$serverId/files/$': typeof AppServerServerIdFilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/discord': typeof DiscordRoute
  '/files': typeof FilesRoute
  '/github': typeof GithubRoute
  '/info': typeof InfoRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/twitter': typeof TwitterRoute
  '/two-factor': typeof TwoFactorRoute
  '/x': typeof XRoute
  '/$': typeof AppSplatRoute
  '/access': typeof AppAccessRoute
  '/bricks': typeof AppBricksRoute
  '/security': typeof AppSecurityRoute
  '/servers': typeof AppServersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sentry-check': typeof ApiSentryCheckRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/relays': typeof AppSettingsRelaysRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/console/$instanceId': typeof ApiConsoleInstanceIdRoute
  '/settings': typeof AppSettingsIndexRoute
  '/server/$serverId/$': typeof AppServerServerIdSplatRoute
  '/server/$serverId/console': typeof AppServerServerIdConsoleRoute
  '/server/$serverId/files': typeof AppServerServerIdFilesRouteWithChildren
  '/server/$serverId/info': typeof AppServerServerIdInfoRoute
  '/server/$serverId/network': typeof AppServerServerIdNetworkRoute
  '/server/$serverId': typeof AppServerServerIdIndexRoute
  '/server/$serverId/files/$': typeof AppServerServerIdFilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/console': typeof ConsoleRoute
  '/discord': typeof DiscordRoute
  '/files': typeof FilesRoute
  '/github': typeof GithubRoute
  '/info': typeof InfoRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/twitter': typeof TwitterRoute
  '/two-factor': typeof TwoFactorRoute
  '/x': typeof XRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/bricks': typeof AppBricksRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/servers': typeof AppServersRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/sentry-check': typeof ApiSentryCheckRoute
  '/_app/server/$serverId': typeof AppServerServerIdRouteWithChildren
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/relays': typeof AppSettingsRelaysRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/console/$instanceId': typeof ApiConsoleInstanceIdRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/server/$serverId/$': typeof AppServerServerIdSplatRoute
  '/_app/server/$serverId/console': typeof AppServerServerIdConsoleRoute
  '/_app/server/$serverId/files': typeof AppServerServerIdFilesRouteWithChildren
  '/_app/server/$serverId/info': typeof AppServerServerIdInfoRoute
  '/_app/server/$serverId/network': typeof AppServerServerIdNetworkRoute
  '/_app/server/$serverId/': typeof AppServerServerIdIndexRoute
  '/_app/server/$serverId/files/$': typeof AppServerServerIdFilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/discord'
    | '/files'
    | '/github'
    | '/info'
    | '/invite'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/twitter'
    | '/two-factor'
    | '/x'
    | '/$'
    | '/access'
    | '/bricks'
    | '/security'
    | '/servers'
    | '/settings'
    | '/api/health'
    | '/api/sentry-check'
    | '/server/$serverId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/relays'
    | '/api/auth/$'
    | '/api/console/$instanceId'
    | '/settings/'
    | '/server/$serverId/$'
    | '/server/$serverId/console'
    | '/server/$serverId/files'
    | '/server/$serverId/info'
    | '/server/$serverId/network'
    | '/server/$serverId/'
    | '/server/$serverId/files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/discord'
    | '/files'
    | '/github'
    | '/info'
    | '/invite'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/twitter'
    | '/two-factor'
    | '/x'
    | '/$'
    | '/access'
    | '/bricks'
    | '/security'
    | '/servers'
    | '/api/health'
    | '/api/sentry-check'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/relays'
    | '/api/auth/$'
    | '/api/console/$instanceId'
    | '/settings'
    | '/server/$serverId/$'
    | '/server/$serverId/console'
    | '/server/$serverId/files'
    | '/server/$serverId/info'
    | '/server/$serverId/network'
    | '/server/$serverId'
    | '/server/$serverId/files/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/console'
    | '/discord'
    | '/files'
    | '/github'
    | '/info'
    | '/invite'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/twitter'
    | '/two-factor'
    | '/x'
    | '/_app/$'
    | '/_app/access'
    | '/_app/bricks'
    | '/_app/security'
    | '/_app/servers'
    | '/_app/settings'
    | '/api/health'
    | '/api/sentry-check'
    | '/_app/server/$serverId'
    | '/_app/settings/account'
    | '/_app/settings/appearance'
    | '/_app/settings/billing'
    | '/_app/settings/relays'
    | '/api/auth/$'
    | '/api/console/$instanceId'
    | '/_app/settings/'
    | '/_app/server/$serverId/$'
    | '/_app/server/$serverId/console'
    | '/_app/server/$serverId/files'
    | '/_app/server/$serverId/info'
    | '/_app/server/$serverId/network'
    | '/_app/server/$serverId/'
    | '/_app/server/$serverId/files/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConsoleRoute: typeof ConsoleRoute
  DiscordRoute: typeof DiscordRoute
  FilesRoute: typeof FilesRoute
  GithubRoute: typeof GithubRoute
  InfoRoute: typeof InfoRoute
  InviteRoute: typeof InviteRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  TwitterRoute: typeof TwitterRoute
  TwoFactorRoute: typeof TwoFactorRoute
  XRoute: typeof XRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSentryCheckRoute: typeof ApiSentryCheckRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiConsoleInstanceIdRoute: typeof ApiConsoleInstanceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twitter': {
      id: '/twitter'
      path: '/twitter'
      fullPath: '/twitter'
      preLoaderRoute: typeof TwitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x': {
      id: '/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof XRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bricks': {
      id: '/_app/bricks'
      path: '/bricks'
      fullPath: '/bricks'
      preLoaderRoute: typeof AppBricksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers': {
      id: '/_app/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AppServersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentry-check': {
      id: '/api/sentry-check'
      path: '/api/sentry-check'
      fullPath: '/api/sentry-check'
      preLoaderRoute: typeof ApiSentryCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/server/$serverId': {
      id: '/_app/server/$serverId'
      path: '/server/$serverId'
      fullPath: '/server/$serverId'
      preLoaderRoute: typeof AppServerServerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/relays': {
      id: '/_app/settings/relays'
      path: '/relays'
      fullPath: '/settings/relays'
      preLoaderRoute: typeof AppSettingsRelaysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/console/$instanceId': {
      id: '/api/console/$instanceId'
      path: '/api/console/$instanceId'
      fullPath: '/api/console/$instanceId'
      preLoaderRoute: typeof ApiConsoleInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/server/$serverId/': {
      id: '/_app/server/$serverId/'
      path: '/'
      fullPath: '/server/$serverId/'
      preLoaderRoute: typeof AppServerServerIdIndexRouteImport
      parentRoute: typeof AppServerServerIdRoute
    }
    '/_app/server/$serverId/$': {
      id: '/_app/server/$serverId/$'
      path: '/$'
      fullPath: '/server/$serverId/$'
      preLoaderRoute: typeof AppServerServerIdSplatRouteImport
      parentRoute: typeof AppServerServerIdRoute
    }
    '/_app/server/$serverId/console': {
      id: '/_app/server/$serverId/console'
      path: '/console'
      fullPath: '/server/$serverId/console'
      preLoaderRoute: typeof AppServerServerIdConsoleRouteImport
      parentRoute: typeof AppServerServerIdRoute
    }
    '/_app/server/$serverId/files': {
      id: '/_app/server/$serverId/files'
      path: '/files'
      fullPath: '/server/$serverId/files'
      preLoaderRoute: typeof AppServerServerIdFilesRouteImport
      parentRoute: typeof AppServerServerIdRoute
    }
    '/_app/server/$serverId/info': {
      id: '/_app/server/$serverId/info'
      path: '/info'
      fullPath: '/server/$serverId/info'
      preLoaderRoute: typeof AppServerServerIdInfoRouteImport
      parentRoute: typeof AppServerServerIdRoute
    }
    '/_app/server/$serverId/network': {
      id: '/_app/server/$serverId/network'
      path: '/network'
      fullPath: '/server/$serverId/network'
      preLoaderRoute: typeof AppServerServerIdNetworkRouteImport
      parentRoute: typeof AppServerServerIdRoute
    }
    '/_app/server/$serverId/files/$': {
      id: '/_app/server/$serverId/files/$'
      path: '/$'
      fullPath: '/server/$serverId/files/$'
      preLoaderRoute: typeof AppServerServerIdFilesSplatRouteImport
      parentRoute: typeof AppServerServerIdFilesRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsRelaysRoute: typeof AppSettingsRelaysRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsRelaysRoute: AppSettingsRelaysRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppServerServerIdFilesRouteChildren {
  AppServerServerIdFilesSplatRoute: typeof AppServerServerIdFilesSplatRoute
}

const AppServerServerIdFilesRouteChildren: AppServerServerIdFilesRouteChildren =
  {
    AppServerServerIdFilesSplatRoute: AppServerServerIdFilesSplatRoute,
  }

const AppServerServerIdFilesRouteWithChildren =
  AppServerServerIdFilesRoute._addFileChildren(
    AppServerServerIdFilesRouteChildren,
  )

interface AppServerServerIdRouteChildren {
  AppServerServerIdSplatRoute: typeof AppServerServerIdSplatRoute
  AppServerServerIdConsoleRoute: typeof AppServerServerIdConsoleRoute
  AppServerServerIdFilesRoute: typeof AppServerServerIdFilesRouteWithChildren
  AppServerServerIdInfoRoute: typeof AppServerServerIdInfoRoute
  AppServerServerIdNetworkRoute: typeof AppServerServerIdNetworkRoute
  AppServerServerIdIndexRoute: typeof AppServerServerIdIndexRoute
}

const AppServerServerIdRouteChildren: AppServerServerIdRouteChildren = {
  AppServerServerIdSplatRoute: AppServerServerIdSplatRoute,
  AppServerServerIdConsoleRoute: AppServerServerIdConsoleRoute,
  AppServerServerIdFilesRoute: AppServerServerIdFilesRouteWithChildren,
  AppServerServerIdInfoRoute: AppServerServerIdInfoRoute,
  AppServerServerIdNetworkRoute: AppServerServerIdNetworkRoute,
  AppServerServerIdIndexRoute: AppServerServerIdIndexRoute,
}

const AppServerServerIdRouteWithChildren =
  AppServerServerIdRoute._addFileChildren(AppServerServerIdRouteChildren)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAccessRoute: typeof AppAccessRoute
  AppBricksRoute: typeof AppBricksRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppServersRoute: typeof AppServersRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppServerServerIdRoute: typeof AppServerServerIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAccessRoute: AppAccessRoute,
  AppBricksRoute: AppBricksRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppServersRoute: AppServersRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppServerServerIdRoute: AppServerServerIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConsoleRoute: ConsoleRoute,
  DiscordRoute: DiscordRoute,
  FilesRoute: FilesRoute,
  GithubRoute: GithubRoute,
  InfoRoute: InfoRoute,
  InviteRoute: InviteRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  TwitterRoute: TwitterRoute,
  TwoFactorRoute: TwoFactorRoute,
  XRoute: XRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSentryCheckRoute: ApiSentryCheckRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiConsoleInstanceIdRoute: ApiConsoleInstanceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
