/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as InfoRouteImport } from './routes/info'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSentryCheckRouteImport } from './routes/api.sentry-check'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSecurityRouteImport } from './routes/_app.security'
import { Route as AppBricksRouteImport } from './routes/_app.bricks'
import { Route as AppAccessRouteImport } from './routes/_app.access'
import { Route as ApiConsoleInstanceIdRouteImport } from './routes/api.console.$instanceId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AppServerIdInfoRouteImport } from './routes/_app.$serverId.info'
import { Route as AppServerIdFilesRouteImport } from './routes/_app.$serverId.files'
import { Route as AppServerIdConsoleRouteImport } from './routes/_app.$serverId.console'
import { Route as AppServerIdFilesSplatRouteImport } from './routes/_app.$serverId.files.$'

const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentryCheckRoute = ApiSentryCheckRouteImport.update({
  id: '/api/sentry-check',
  path: '/api/sentry-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppBricksRoute = AppBricksRouteImport.update({
  id: '/bricks',
  path: '/bricks',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const ApiConsoleInstanceIdRoute = ApiConsoleInstanceIdRouteImport.update({
  id: '/api/console/$instanceId',
  path: '/api/console/$instanceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServerIdInfoRoute = AppServerIdInfoRouteImport.update({
  id: '/$serverId/info',
  path: '/$serverId/info',
  getParentRoute: () => AppRoute,
} as any)
const AppServerIdFilesRoute = AppServerIdFilesRouteImport.update({
  id: '/$serverId/files',
  path: '/$serverId/files',
  getParentRoute: () => AppRoute,
} as any)
const AppServerIdConsoleRoute = AppServerIdConsoleRouteImport.update({
  id: '/$serverId/console',
  path: '/$serverId/console',
  getParentRoute: () => AppRoute,
} as any)
const AppServerIdFilesSplatRoute = AppServerIdFilesSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppServerIdFilesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/files': typeof FilesRoute
  '/info': typeof InfoRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/two-factor': typeof TwoFactorRoute
  '/access': typeof AppAccessRoute
  '/bricks': typeof AppBricksRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sentry-check': typeof ApiSentryCheckRoute
  '/$serverId/console': typeof AppServerIdConsoleRoute
  '/$serverId/files': typeof AppServerIdFilesRouteWithChildren
  '/$serverId/info': typeof AppServerIdInfoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/console/$instanceId': typeof ApiConsoleInstanceIdRoute
  '/$serverId/files/$': typeof AppServerIdFilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/files': typeof FilesRoute
  '/info': typeof InfoRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/two-factor': typeof TwoFactorRoute
  '/access': typeof AppAccessRoute
  '/bricks': typeof AppBricksRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sentry-check': typeof ApiSentryCheckRoute
  '/$serverId/console': typeof AppServerIdConsoleRoute
  '/$serverId/files': typeof AppServerIdFilesRouteWithChildren
  '/$serverId/info': typeof AppServerIdInfoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/console/$instanceId': typeof ApiConsoleInstanceIdRoute
  '/$serverId/files/$': typeof AppServerIdFilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/console': typeof ConsoleRoute
  '/files': typeof FilesRoute
  '/info': typeof InfoRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/two-factor': typeof TwoFactorRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/bricks': typeof AppBricksRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sentry-check': typeof ApiSentryCheckRoute
  '/_app/$serverId/console': typeof AppServerIdConsoleRoute
  '/_app/$serverId/files': typeof AppServerIdFilesRouteWithChildren
  '/_app/$serverId/info': typeof AppServerIdInfoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/console/$instanceId': typeof ApiConsoleInstanceIdRoute
  '/_app/$serverId/files/$': typeof AppServerIdFilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/files'
    | '/info'
    | '/invite'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/two-factor'
    | '/access'
    | '/bricks'
    | '/security'
    | '/settings'
    | '/api/health'
    | '/api/sentry-check'
    | '/$serverId/console'
    | '/$serverId/files'
    | '/$serverId/info'
    | '/api/auth/$'
    | '/api/console/$instanceId'
    | '/$serverId/files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/files'
    | '/info'
    | '/invite'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/two-factor'
    | '/access'
    | '/bricks'
    | '/security'
    | '/settings'
    | '/api/health'
    | '/api/sentry-check'
    | '/$serverId/console'
    | '/$serverId/files'
    | '/$serverId/info'
    | '/api/auth/$'
    | '/api/console/$instanceId'
    | '/$serverId/files/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/console'
    | '/files'
    | '/info'
    | '/invite'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/two-factor'
    | '/_app/access'
    | '/_app/bricks'
    | '/_app/security'
    | '/_app/settings'
    | '/api/health'
    | '/api/sentry-check'
    | '/_app/$serverId/console'
    | '/_app/$serverId/files'
    | '/_app/$serverId/info'
    | '/api/auth/$'
    | '/api/console/$instanceId'
    | '/_app/$serverId/files/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConsoleRoute: typeof ConsoleRoute
  FilesRoute: typeof FilesRoute
  InfoRoute: typeof InfoRoute
  InviteRoute: typeof InviteRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  TwoFactorRoute: typeof TwoFactorRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSentryCheckRoute: typeof ApiSentryCheckRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiConsoleInstanceIdRoute: typeof ApiConsoleInstanceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentry-check': {
      id: '/api/sentry-check'
      path: '/api/sentry-check'
      fullPath: '/api/sentry-check'
      preLoaderRoute: typeof ApiSentryCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bricks': {
      id: '/_app/bricks'
      path: '/bricks'
      fullPath: '/bricks'
      preLoaderRoute: typeof AppBricksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/console/$instanceId': {
      id: '/api/console/$instanceId'
      path: '/api/console/$instanceId'
      fullPath: '/api/console/$instanceId'
      preLoaderRoute: typeof ApiConsoleInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$serverId/info': {
      id: '/_app/$serverId/info'
      path: '/$serverId/info'
      fullPath: '/$serverId/info'
      preLoaderRoute: typeof AppServerIdInfoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$serverId/files': {
      id: '/_app/$serverId/files'
      path: '/$serverId/files'
      fullPath: '/$serverId/files'
      preLoaderRoute: typeof AppServerIdFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$serverId/console': {
      id: '/_app/$serverId/console'
      path: '/$serverId/console'
      fullPath: '/$serverId/console'
      preLoaderRoute: typeof AppServerIdConsoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$serverId/files/$': {
      id: '/_app/$serverId/files/$'
      path: '/$'
      fullPath: '/$serverId/files/$'
      preLoaderRoute: typeof AppServerIdFilesSplatRouteImport
      parentRoute: typeof AppServerIdFilesRoute
    }
  }
}

interface AppServerIdFilesRouteChildren {
  AppServerIdFilesSplatRoute: typeof AppServerIdFilesSplatRoute
}

const AppServerIdFilesRouteChildren: AppServerIdFilesRouteChildren = {
  AppServerIdFilesSplatRoute: AppServerIdFilesSplatRoute,
}

const AppServerIdFilesRouteWithChildren =
  AppServerIdFilesRoute._addFileChildren(AppServerIdFilesRouteChildren)

interface AppRouteChildren {
  AppAccessRoute: typeof AppAccessRoute
  AppBricksRoute: typeof AppBricksRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppServerIdConsoleRoute: typeof AppServerIdConsoleRoute
  AppServerIdFilesRoute: typeof AppServerIdFilesRouteWithChildren
  AppServerIdInfoRoute: typeof AppServerIdInfoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessRoute: AppAccessRoute,
  AppBricksRoute: AppBricksRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppServerIdConsoleRoute: AppServerIdConsoleRoute,
  AppServerIdFilesRoute: AppServerIdFilesRouteWithChildren,
  AppServerIdInfoRoute: AppServerIdInfoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConsoleRoute: ConsoleRoute,
  FilesRoute: FilesRoute,
  InfoRoute: InfoRoute,
  InviteRoute: InviteRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  TwoFactorRoute: TwoFactorRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSentryCheckRoute: ApiSentryCheckRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiConsoleInstanceIdRoute: ApiConsoleInstanceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
